[project]
name = "falcon-twig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.0.0",
    "transformers>=4.56.0",
    "pydantic>=2.6.0",
    "accelerate>=0.34",
    "peft>=0.11.1",
    "bitsandbytes>=0.43.1",
    "evaluate",
    "jsonlines",
    "tqdm",
    "typer>=0.12",
]

[tool.uv]
dev-dependencies = [
  "ruff",
  "pytest",
]
